Repository thecyberworld/thecyberhub-app, pull requests merged in 2022-10, with the labels that each got.

#7 Ath.homescreen tab nav
  App.js
  navigation/MainContainer.js
  package-lock.json
  package.json
  screens/DetailsScreen.js
  screens/HomeScreen.js
  styles/colors.js
  styles/spacing.js
  styles/styles.js
  styles/typography.js
Labels: hacktoberfest-accepted, hacktoberfest

#10 Add app icons and splash image.
  App.js
  app.json
  assets/adaptive-icon.png
  assets/icon.png
  assets/splash.png
  screens/HomeScreen.js
Labels: hacktoberfest-accepted, hacktoberfest

#19 add: Events screen design
  assets/Capture.png
  navigation/MainContainer.js
  screens/EventsScreen.tsx
  screens/EventsScreenStyles.ts
Labels: 🥗 status: ready for merge, hacktoberfest, hacktoberfest-accepted

#40 settings page
  navigation/MainContainer.js
  package-lock.json
  screens/SettingsScreen.js
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest

#42 Jobs internships page
  components/JobCard.tsx
  components/styles.ts
  navigation/MainContainer.js
  package-lock.json
  package.json
  screens/JobsScreen.tsx
  utils/jobsData.tsx
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest-accepted, hacktoberfest
